# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

#target 'HealthTracker' do
def pod_file
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthTracker


pod 'GoogleMaps'
pod 'SDWebImage', '~> 5.11'
pod 'PusherSwift'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'MessageKit'
pod 'AEOTPTextField'
end

target 'HealthTracker' do
  pod_file
end

target 'HealthTrackerDev' do
  pod_file
end
